POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByaW5jeTEyM0BnbWFpbC5jb20iLCJleHAiOjE3NDg1MDQxNjIsImlkIjozfQ.oy1Ku6c_cI31EO0p0ZtgQ-AYVKLwEmmIw-_YJVCci3s


{
  "name": "Test Event ANsha vaishnavi low",
  "description": "This is a test event qee",
  "date": "2023-10-01T10:00:00Z",
  "location": "Test Location"
}